name: Develop
on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Load Cached Dependencies
        id: dependency-cache
        uses: ./.github/actions/dependency-cache
      - name: Install Dependencies
        if: ${{ steps.dependency-cache.outputs.cache-hit != 'true' }}
        run: npm ci
  lint:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Dependencies
        uses: ./.github/actions/dependency-cache
      - name: Run Lint
        run: npm run lint
  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Dependencies
        uses: ./.github/actions/dependency-cache
      - name: Run Tests
        run: npm test
  package:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Dependencies
        uses: ./.github/actions/dependency-cache
      - name: Build
        run: npm run build
      - name: Package
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: |
            dist
            Dockerfile
  publish:
    runs-on: ubuntu-latest
    needs: [package]
    if: github.ref_name == 'main'
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: artifact
      - name: Build Image
        run: docker build -t ${{ secrets.DOCKER_USER }}/viteapp-react:latest .
      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKER_USER}} -p ${{ secrets.DOCKER_PASS}}
      - name: Publish Image
        run: docker push ${{ secrets.DOCKER_USER }}/viteapp-react
